prooph_event_store:
    stores:
        default_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            repositories:
                product_repository:
                    repository_class: App\Infrastructure\Repository\EventStoreProductRepository
                    aggregate_type: App\Core\Component\Product\Domain\Model\Product\Product
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
    projection_managers:
        default_projection_manager:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore # event store
            connection: 'doctrine.pdo.connection'
            projections:
                product_projection:
                    read_model: App\Infrastructure\Projection\Product\ProductReadModel
                    projection: App\Infrastructure\Projection\Product\ProductProjection

services:
    Prooph\EventStore\Pdo\MySqlEventStore:
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator